version: "3.9"
services:
  backend:
    build: ./backend
    ports:
     - "8080:8080"

  frontend:
    build: ./frontend
    ports:
      - "5173:3000"

  redis:
    image: redis
  # TODO: Create config for frontend